flags: {}

nix:
  shell-file: shell.nix

extra-package-dbs: []

packages:
- '.'
- location:
    git: https://github.com/serokell/universum
    commit: db3cd301545e5da000e53ca2cdf274e0386192bf
  extra-dep: true

extra-deps:
- equational-reasoning-0.4.1.1
- ghc-typelits-natnormalise-0.4.6
- ghc-typelits-presburger-0.1.1.0
- hmatrix-0.18.0.0
- monomorphic-0.0.3.3
- type-natural-0.7.1.1
- vector-sized-0.4.1.0
- chatter-0.9.0.0
- stemmer-0.5.2
- fullstop-0.1.4
- tokenize-0.3.0
- cereal-0.5.2.0

resolver: lts-7.13
